version: "3.3"
services:

  delugevpn:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.10
        aliases:
          - delugevpn
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58946:58946
      - 8888:8888/tcp
      - 8388:8388/udp
      - 8000:8000/tcp
    container_name: delugevpn
    volumes:
      - ./docker/downloads:/downloads
      - ./docker/config/deluge:/config
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=x6920908
      - VPN_PASS=pUgjTruKvg
      - VPN_PROV=pia
      - STRICT_PORT_FORWARD=no
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=10.0.0.0/8
      - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - ADDITIONAL_PORTS=1234
      - DEBUG=false
      - UMASK=022
      - PUID=2000
      - PGID=2000
    image: binhex/arch-delugevpn
    restart: unless-stopped

  sonarr:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.20
        aliases:
          - sonarr
    image: mdhiggins/sonarr-sma
    container_name: sonarr
    volumes:
      - ./docker/config/sonarr:/config
      - ./docker/config/sma:/usr/local/sma/config
      - ./docker/media/tvshows:/tv
      - ./docker/downloads:/downloads
    restart: unless-stopped
    environment:
      - PUID=2000
      - PGID=2000
    depends_on:
      - delugevpn
    ports:
      - 8989:8989

  jackett:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.30
        aliases:
          - jackett
    container_name: jackett
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/Chicago
      - AUTO_UPDATE=true
    volumes:
      - ./docker/config/jackett:/config/Jackett
      - ./docker/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    image: linuxserver/jackett

  radarr:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.40
        aliases:
          - radarr
    image: mdhiggins/radarr-sma
    container_name: radarr
    volumes:
      - ./docker/config/radarr:/config
      - ./docker/config/sma:/usr/local/sma/config
      - ./docker/media/movies:/movies
      - ./docker/downloads:/downloads
    restart: unless-stopped
    environment:
      - PUID=2000
      - PGID=2000
    ports:
      - 7878:7878

  plex:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.50
        aliases:
          - plex
    container_name: plex
    hostname: plex
    ports:
      - 32400:32400
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=claim-By8WWAuZHfFjy7sNSsMh
      - PUID=2000
      - PGID=2000
    volumes:
      - ./docker/config/plex:/config
      - ./docker/config/plex/transcode:/transcode
      - ./docker/media:/data
      #- '/mnt/easystore/kodi/TV Shows:/tv'
      #- '/mnt/easystore/kodi/Movies:/movies'
      #- '/mnt/easystore/kodi/Cancelled:/cancelled'
      #- '/mnt/easystore/kodi/Old:/old'
    image: plexinc/pms-docker
    restart: unless-stopped

  tautulli:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.60
        aliases:
          - tautulli
    container_name: tautulli
    volumes:
      - ./docker/config/plexpy:/config
      - ./docker/logs/plexpy:/logs:ro
    environment:
      - PGID=2000
      - PUID=2000
      - TZ=<timezone>
    ports:
      - 8181:8181
    image: linuxserver/tautulli
    restart: unless-stopped

  nzbget:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.70
        aliases:
          - nzbget
    container_name: nzbget
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/Chicago
    image: linuxserver/nzbget
    restart: unless-stopped
    ports:
      - 6789:6789
    volumes:
      - ./docker/config/nzbget/scripts:/app/nzbget/share/nzbget/scripts
      - ./docker/config/nzbget:/config
      - ./docker/downloads:/downloads

  nginx:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.250
        aliases:
          - nginx
    container_name: ngingx
    depends_on:
      - delugevpn
      - sonarr
      - jackett
      - radarr
      - plex
      - tautulli
      - nzbget
    environment:
      - NGINX_LISTEN_PORT=65456
      - DELUGEVPN_LISTEN_PORT=8112
      - SONARR_LISTEN_PORT=8989
      - JACKETT_LISTEN_PORT=9117
      - RADARR_LISTEN_PORT=7878
      - PLEX_LISTEN_PORT=32400
      - TAUTULLI_LISTEN_PORT=8181
      - NZBGET_LISTEN_PORT=6789
      - UMASK=022
      - PUID=2000
      - PGID=2000
    image: mmxca/nginx-mc
    volumes:
      - ./docker/nginx:/run/nginx
      - ./docker/config/nginx:/etc/nginx
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      - 65456:65456
    restart: unless-stopped

  plexcleaner:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.90
        aliases:
          - plexcleaner
    container_name: plexcleaner
    image: mmxca/media-center-plexcleaner:latest
    restart: unless-stopped
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/Chicago
      - PLEX_VIDEO_CLEANER_DAYS_TO_RETAIN=1
      - PLEX_VIDEO_CLEANER_PERCENT_THRESHOLD=98
      - PLEX_VIDEO_CLEANER_SLEEP=10
      - PLEX_VIDEO_CLEANER_DEBUG=true
      - PLEX_VIDEO_CLEANER_SHOWS=true
      - PLEX_VIDEO_CLEANER_MOVIES=false
      - PLEX_VIDEO_CLEANER_BASEURL=http://plex:32400
      - PLEX_VIDEO_CLEANER_TOKEN=s7-vJyb8e_nj57VyyFqb
      #- PLEX_VIDEO_CLEANER_USERNAME=
      #- PLEX_VIDEO_CLEANER_PASSWORD=
    volumes:
      - ./docker/logs/plexcleaner:/logs

networks:
  kodi_server:
    ipam:
      driver: default
      config:
        - subnet: "192.168.2.0/24"
