version: "3.3"
services:

  delugevpn:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.10
        aliases:
          - delugevpn
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58946:58946
      - 8888:8888/tcp
      - 8388:8388/udp
      - 8000:8000/tcp
    container_name: delugevpn
    volumes:
      - ./docker/downloads:/downloads
      - ./docker/config/deluge:/config
      # - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    env_file:
      - environment_variables
    image: binhex/arch-delugevpn
    restart: unless-stopped

  sonarr:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.20
        aliases:
          - sonarr
    image: mdhiggins/sonarr-sma
    container_name: sonarr
    volumes:
      - ./docker/config/sonarr:/config
      - ./docker/config/sma:/usr/local/sma/config
      - ./docker/media/tvshows:/tv
      - ./docker/downloads:/downloads
    restart: unless-stopped
    env_file:
      - environment_variables
    depends_on:
      - delugevpn
    ports:
      - 8989:8989

  jackett:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.30
        aliases:
          - jackett
    container_name: jackett
    env_file:
      - environment_variables
    volumes:
      - ./docker/config/jackett:/config/Jackett
      - ./docker/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    image: linuxserver/jackett

  radarr:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.40
        aliases:
          - radarr
    image: mdhiggins/radarr-sma
    container_name: radarr
    volumes:
      - ./docker/config/radarr:/config
      - ./docker/config/sma:/usr/local/sma/config
      - ./docker/media/movies:/movies
      - ./docker/downloads:/downloads
    restart: unless-stopped
    env_file:
      - environment_variables
    ports:
      - 7878:7878

  plex:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.50
        aliases:
          - plex
    container_name: plex
    hostname: plex
    ports:
      - 32400:32400
    env_file:
      - environment_variables
    volumes:
      - ./docker/config/plex:/config
      - ./docker/config/plex/transcode:/transcode
      - ./docker/media:/data
      #- '/mnt/easystore/kodi/TV Shows:/tv'
      #- '/mnt/easystore/kodi/Movies:/movies'
      #- '/mnt/easystore/kodi/Cancelled:/cancelled'
      #- '/mnt/easystore/kodi/Old:/old'
    image: plexinc/pms-docker
    restart: unless-stopped

  tautulli:
    networks:
      kodi_server:
        ipv4_address: 192.168.2.60
        aliases:
          - tautulli
    container_name: tautulli
    volumes:
      - ./docker/config/plexpy:/config
      - ./docker/logs/plex:/logs:ro
    env_file:
      - environment_variables
    ports:
      - 8181:8181
    image: linuxserver/tautulli
    restart: unless-stopped

  nzbget:
    build:
      context: .
      dockerfile: NzbGet.Dockerfile
    networks:
      kodi_server:
        ipv4_address: 192.168.2.70
        aliases:
          - nzbget
    container_name: nzbget
    env_file:
      - environment_variables
    image: linuxserver/nzbget
    restart: unless-stopped
    ports:
      - 6789:6789
    volumes:
      - ./docker/config/nzbget/scripts:/app/nzbget/share/nzbget/scripts
      - ./docker/config/nzbget:/config
      - ./docker/downloads:/downloads

  nginx:
    build:
      context: nginx
    networks:
      kodi_server:
        ipv4_address: 192.168.2.250
        aliases:
          - nginx
    container_name: ngingx
    depends_on:
      - delugevpn
      - sonarr
      - jackett
      - radarr
      - plex
      - tautulli
      - nzbget
    env_file:
      - environment_variables
    image: mmxca/nginx:custom
    volumes:
      - ./docker/nginx:/run/nginx
      - ./docker/config/nginx:/etc/nginx
      - ./docker/config/nginx/certbot:/etc/letsencrypt
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      - 65456:65456
      - 443:443
    restart: unless-stopped

  # plexcleaner:
  #   networks:
  #     kodi_server:
  #       ipv4_address: 192.168.2.80
  #       aliases:
  #         - plexcleaner
  #   container_name: plexcleaner
  #   image: mmxca/media-center-plexcleaner:latest
  #   restart: unless-stopped
  #   env_file:
  #     - environment_variables
  #   volumes:
  #     - /home/dhoffman/docker/logs/plexcleaner:/logs

networks:
  kodi_server:
    ipam:
      driver: default
      config:
        - subnet: "192.168.2.0/24"
